version: "3.5"
   
services:

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    env_file:
      - ./docker/.postgres
    ports:
      - 5432:5432

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: sh ./docker/run_web.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./docker/.web
      - ./docker/.postgres
    depends_on:
      - postgres
